apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: virtual-dev-cluster-1-aws-ssm
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
