apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aws-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: aws-production description
  sourceNamespaces: ["aws-production-environment"]
  sourceRepos:
  - 'https://github.com/barclays-corp/barclays-corp-gitops.git'
  destinations:
  - name: aws-production
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - description: aws-production-admin-role
    groups:
    - admins
    name: admin-role
    policies:
    - p, proj:aws-production:admin-role, applications, *, aws-production/*, allow
