apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aws-preprod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: aws-preprod description
  sourceNamespaces: ["aws-preprod-environment"]
  sourceRepos:
  - 'https://github.com/barclays-corp/barclays-corp-gitops.git'
  - 'oci://555935582951.dkr.ecr.us-west-2.amazonaws.com/barclays-corp/charts/zippy'
  destinations:
  - name: aws-preprod
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - description: aws-preprod-admin-role
    groups:
    - admins
    name: admin-role
    policies:
    - p, proj:aws-preprod:admin-role, applications, *, aws-preprod/*, allow
