apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: test-gitlab
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: test-gitlab description
  destinations:
  - name: test-gitlab
    namespace: '*'
  roles:
  - description: test-gitlab-admin-role
    groups:
    - admins
    name: admin-role
    policies:
    - p, proj:test-gitlab:admin-role, applications, *, test-gitlab/*, allow
  sourceNamespaces:
  - test-gitlab-environment
  sourceRepos:
  - https://github.com/barclays-corp/barclays-corp-gitops.git
  - https://kubernetes.github.io/autoscaler
