apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: virtual-dev-cluster-1-infrastructure
spec:
  providerConfigRef:
    name: virtual-dev-cluster-1
  forProvider:
    source: Remote
    module: git::https://github.com/gitops-ing/barclays-corp-gitops.git//terraform/aws/modules/workload-vcluster?ref=main
    vars:
    - key: vcluster_name
      value: "virtual-dev-cluster-1"
    - key: host_cluster
      value: "sandbox-host"
    - key: domain_name
      value: "gitops.ing"
