apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: demoday
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::555935582951:role/eso-demoday-one
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-private
  namespace: demoday
spec:
  region: us-west-2
  role: arn:aws:iam::555935582951:role/eso-demoday-one
  scope: private
  auth:
    jwt:
      serviceAccountRef:
        name: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecr-auth
  namespace: demoday
spec:
  refreshInterval: "1h"
  target:
    name: ecr-auth
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          expiresAt: "{{ .expires_at }}"
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .proxy_endpoint | replace "https://" "" }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-private
