apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: test-catalog-aws-secret-manager
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    aws:
      service: ParameterStore
      region: lon1
      role: arn:aws:iam:::role/eso-test-catalog
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-operator
