apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: civo-barclays-priv-region-test-reloader
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: civo-barclays-priv-region-test-platform
  source:
    repoURL: 'https://stakater.github.io/stakater-charts'
    targetRevision: v1.0.10
    chart: reloader
    helm:
      values: |-
        ignoreSecrets: false
  destination:
    name: civo-barclays-priv-region-test
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
