apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-catalog-external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: test-catalog-platform
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.14.4
    helm:
      releaseName: external-dns
      values: |
        image:
          repository: registry.k8s.io/external-dns/external-dns
          tag: "v0.13.2"
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::126827061464:role/external-dns-test-catalog'
        provider: aws
        sources:
        - ingress
        domainFilters:
        - gitops.ing
    chart: external-dns
  destination:
    name: test-catalog
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
