apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-preprod-aws-secret-manager
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      role: arn:aws:iam::555935582951:role/eso-aws-preprod
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-operator
