apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: civo-preprod-public-aws-secret-manager
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    aws:
      service: ParameterStore
      region: nyc1
      role: arn:aws:iam:::role/eso-civo-preprod-public
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-operator
