apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: civo-preprod-public-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://github.com/gitops-ing/barclays-corp-gitops
    path: registry/clusters/civo-preprod-public/infrastructure
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: civo-preprod-public
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 30
      backoff:
        duration: 1m
        factor: 1

