apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: civo-private-dryrun-1-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://github.com/gitops-ing/barclays-corp-gitops
    path: registry/clusters/civo-private-dryrun-1/infrastructure
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: civo-private-dryrun-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
