apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: civo-barclays-priv-region-test-aws-secret-manager
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    aws:
      service: ParameterStore
      region: barclays-lon1
      role: arn:aws:iam:::role/eso-civo-barclays-priv-region-test
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-operator
