apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.workloadClusterName }}-reloader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: {{ .Values.workloadClusterName }}-platform
  source:
    repoURL: 'https://stakater.github.io/stakater-charts'
    targetRevision: {{ .Values.reloaderVersion }}
    chart: reloader
    helm:
      values: |-
        ignoreSecrets: false
  destination:
    name: {{ .Values.workloadClusterName }}
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
